### ISSUE TITLE
Standalone Takes A Long Time to display

### ISSUE THREAD

**Issue by krisnotepad** [stephomi/sculptgl#58]
My OS is **win10**, but when I setup the stanalone,  it takes **more than 45 sec** before the main page display.
What's worse, it takes even several minutes in win7. Is it something wrong and how to fix it? Thnaks in advance?
![image](https://user-images.githubusercontent.com/32287002/30842231-70739fb0-a2b3-11e7-9348-db1ea7fdaf10.png)

**Comment by stephomi** [comment]
I had the issue at some point too, but I never dig it more than that as I didn't want to spend time on the automatic standalone build.

The issue is somewhat coming from electron https://github.com/electron/electron/issues/6340
I'm pretty sure there is an easy fix as the loading time is really really long indeed

**Comment by krisnotepad** [comment]
Thanks your advice and it may has little anything to to with  electron. I have check the code and found that it may the link to google and the language packs. 

My network is not good enough(especial in LAN), while **index.html** and **authSuccess.html**, which would always try to connect to google, take quite a long time when starting up. Also, the language packs contribute. 

After annotating corresponding code, this app's loading time could compete with some native ones.
