### ISSUE TITLE
remesh can result in non manifold geometry

### ISSUE THREAD

**Issue by selfsame** [stephomi/sculptgl#69]
To reproduce, open http://selfsamegames.com/temp/non-manifold.sgl, select the cylinder, and remesh. (I use blender's `select non manifold` command to check for non manifold vertices)

The example file has very bad geometry, but I've found that this can happen under normal sculpting situations or when remeshing multiple objects together.

**Comment by stephomi** [comment]
Yes the remeshing algorithm can produce non manifold vertices.
https://0fps.net/2012/07/12/smooth-voxel-terrain-part-2/ (surfaceNets)

It's a known issue but unfortunately there is no easy fix.
It would probably require another algorithm (manifold dual contouring, marching cube, etc)

**Comment by stephomi** [comment]
A quick hack to produce manifold mesh with marching cube https://github.com/stephomi/sculptgl/commit/772b650ad7fb7a0bde642c11772034226ef66bdb
 (from https://github.com/mikolalysenko/isosurface/blob/master/lib/marchingcubes.js)

Marching cube has uglier pattern but it looks manfold.
For some reasons, the algorithm outputs a triangle soup instead of shared vertices (you can simply export to stl and re-import stl in sgl, it'll weld vertices).

I'm not really active anymore on sculptgl but I'll try to add this algo as an alternative way to remesh, should be quick.
Just need to clean the code and weld those vertices.

**Comment by stephomi** [comment]
Added marching cubes remeshing in https://github.com/stephomi/sculptgl/commit/27afc25a111f36e32f82ff41b3d48eaa9f572722
